# Generated by Django 4.1 on 2022-08-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='university',
            field=models.CharField(default='public university', max_length=100),
        ),
    ]
