# Generated by Django 4.1 on 2022-08-31 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_candidate_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='voters',
        ),
    ]
