# Generated by Django 4.1 on 2022-08-31 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_remove_candidate_voters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='ballotNumber',
        ),
    ]
