# Generated by Django 4.1 on 2022-09-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_remove_candidate_ballotnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='maxVotes',
            new_name='maxCandidates',
        ),
    ]
